ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19014

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 30, in attach_oss_fuzz_bug_report
    report = parse_oss_fuzz_bug_report_details(issue)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 51, in parse_oss_fuzz_bug_report_details
    fuzzing_engine = _get_fuzzing_engine(description, id)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 102, in _get_fuzzing_engine
    return capture(description, r'Fuzzing Engine: (.+?)[\n$]')
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/utils/string_util.py", line 7, in capture
    captured_text = match.group(groupnum)
AttributeError: 'NoneType' object has no attribute 'group'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19051

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 30, in attach_oss_fuzz_bug_report
    report = parse_oss_fuzz_bug_report_details(issue)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 57, in parse_oss_fuzz_bug_report_details
    crash_state = _get_crash_state(description)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 135, in _get_crash_state
    raw_crash_state = capture(description, r'Crash State:\n(.*?)\n  \n', pattern_flags=re.DOTALL)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/utils/string_util.py", line 7, in capture
    captured_text = match.group(groupnum)
AttributeError: 'NoneType' object has no attribute 'group'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19113

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 30, in attach_oss_fuzz_bug_report
    report = parse_oss_fuzz_bug_report_details(issue)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 57, in parse_oss_fuzz_bug_report_details
    crash_state = _get_crash_state(description)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 135, in _get_crash_state
    raw_crash_state = capture(description, r'Crash State:\n(.*?)\n  \n', pattern_flags=re.DOTALL)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/utils/string_util.py", line 7, in capture
    captured_text = match.group(groupnum)
AttributeError: 'NoneType' object has no attribute 'group'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19114

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 30, in attach_oss_fuzz_bug_report
    report = parse_oss_fuzz_bug_report_details(issue)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 57, in parse_oss_fuzz_bug_report_details
    crash_state = _get_crash_state(description)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 135, in _get_crash_state
    raw_crash_state = capture(description, r'Crash State:\n(.*?)\n  \n', pattern_flags=re.DOTALL)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/utils/string_util.py", line 7, in capture
    captured_text = match.group(groupnum)
AttributeError: 'NoneType' object has no attribute 'group'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19121

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 27, in attach_oss_fuzz_bug_report
    if not is_oss_fuzz_bug_report(issue):
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 40, in is_oss_fuzz_bug_report
    is_nonsecurity_bug_report = almost_equal("Bug", issue.metadata['Type'])
KeyError: 'Type'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19192

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 30, in attach_oss_fuzz_bug_report
    report = parse_oss_fuzz_bug_report_details(issue)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 57, in parse_oss_fuzz_bug_report_details
    crash_state = _get_crash_state(description)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 135, in _get_crash_state
    raw_crash_state = capture(description, r'Crash State:\n(.*?)\n  \n', pattern_flags=re.DOTALL)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/utils/string_util.py", line 7, in capture
    captured_text = match.group(groupnum)
AttributeError: 'NoneType' object has no attribute 'group'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19277

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 30, in attach_oss_fuzz_bug_report
    report = parse_oss_fuzz_bug_report_details(issue)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 51, in parse_oss_fuzz_bug_report_details
    fuzzing_engine = _get_fuzzing_engine(description, id)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 102, in _get_fuzzing_engine
    return capture(description, r'Fuzzing Engine: (.+?)[\n$]')
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/utils/string_util.py", line 7, in capture
    captured_text = match.group(groupnum)
AttributeError: 'NoneType' object has no attribute 'group'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19429

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 30, in attach_oss_fuzz_bug_report
    report = parse_oss_fuzz_bug_report_details(issue)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 57, in parse_oss_fuzz_bug_report_details
    crash_state = _get_crash_state(description)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 135, in _get_crash_state
    raw_crash_state = capture(description, r'Crash State:\n(.*?)\n  \n', pattern_flags=re.DOTALL)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/utils/string_util.py", line 7, in capture
    captured_text = match.group(groupnum)
AttributeError: 'NoneType' object has no attribute 'group'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19475

ERROR:root:Traceback (most recent call last):
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/issue/issue_scraper.py", line 57, in scrape
    issue_elem = self._get_issue_elem(issue_url, loading_delay)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/issue/issue_scraper.py", line 136, in _get_issue_elem
    raise e
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/issue/issue_scraper.py", line 128, in _get_issue_elem
    issue_elem = mr_issue_page_shadow.find_element_by_id('issue')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 176, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 658, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="issue"]"}
  (Session info: chrome=85.0.4183.83)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 41, in main
    issue_i = issue_scraper.scrape(url_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/issue/issue_scraper.py", line 59, in scrape
    raise ScrapeException(f"Unable to scrape issue at {issue_url}. "
issue.issue_scraper.ScrapeException: 'Unable to scrape issue at https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19475. Check whether issue exists and is publically available.'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19496

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 30, in attach_oss_fuzz_bug_report
    report = parse_oss_fuzz_bug_report_details(issue)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 57, in parse_oss_fuzz_bug_report_details
    crash_state = _get_crash_state(description)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 135, in _get_crash_state
    raw_crash_state = capture(description, r'Crash State:\n(.*?)\n  \n', pattern_flags=re.DOTALL)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/utils/string_util.py", line 7, in capture
    captured_text = match.group(groupnum)
AttributeError: 'NoneType' object has no attribute 'group'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19685

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 30, in attach_oss_fuzz_bug_report
    report = parse_oss_fuzz_bug_report_details(issue)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 57, in parse_oss_fuzz_bug_report_details
    crash_state = _get_crash_state(description)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 135, in _get_crash_state
    raw_crash_state = capture(description, r'Crash State:\n(.*?)\n  \n', pattern_flags=re.DOTALL)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/utils/string_util.py", line 7, in capture
    captured_text = match.group(groupnum)
AttributeError: 'NoneType' object has no attribute 'group'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19719

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 30, in attach_oss_fuzz_bug_report
    report = parse_oss_fuzz_bug_report_details(issue)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 57, in parse_oss_fuzz_bug_report_details
    crash_state = _get_crash_state(description)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 135, in _get_crash_state
    raw_crash_state = capture(description, r'Crash State:\n(.*?)\n  \n', pattern_flags=re.DOTALL)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/utils/string_util.py", line 7, in capture
    captured_text = match.group(groupnum)
AttributeError: 'NoneType' object has no attribute 'group'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19728

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 30, in attach_oss_fuzz_bug_report
    report = parse_oss_fuzz_bug_report_details(issue)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 57, in parse_oss_fuzz_bug_report_details
    crash_state = _get_crash_state(description)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 135, in _get_crash_state
    raw_crash_state = capture(description, r'Crash State:\n(.*?)\n  \n', pattern_flags=re.DOTALL)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/utils/string_util.py", line 7, in capture
    captured_text = match.group(groupnum)
AttributeError: 'NoneType' object has no attribute 'group'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19770

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 27, in attach_oss_fuzz_bug_report
    if not is_oss_fuzz_bug_report(issue):
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 40, in is_oss_fuzz_bug_report
    is_nonsecurity_bug_report = almost_equal("Bug", issue.metadata['Type'])
KeyError: 'Type'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19804

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 30, in attach_oss_fuzz_bug_report
    report = parse_oss_fuzz_bug_report_details(issue)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 57, in parse_oss_fuzz_bug_report_details
    crash_state = _get_crash_state(description)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 135, in _get_crash_state
    raw_crash_state = capture(description, r'Crash State:\n(.*?)\n  \n', pattern_flags=re.DOTALL)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/utils/string_util.py", line 7, in capture
    captured_text = match.group(groupnum)
AttributeError: 'NoneType' object has no attribute 'group'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19864

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 30, in attach_oss_fuzz_bug_report
    report = parse_oss_fuzz_bug_report_details(issue)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 57, in parse_oss_fuzz_bug_report_details
    crash_state = _get_crash_state(description)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 135, in _get_crash_state
    raw_crash_state = capture(description, r'Crash State:\n(.*?)\n  \n', pattern_flags=re.DOTALL)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/utils/string_util.py", line 7, in capture
    captured_text = match.group(groupnum)
AttributeError: 'NoneType' object has no attribute 'group'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19873

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 30, in attach_oss_fuzz_bug_report
    report = parse_oss_fuzz_bug_report_details(issue)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 50, in parse_oss_fuzz_bug_report_details
    project = _get_project(description, id)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 85, in _get_project
    return capture(description, r'Project: (.+?)[\n$]')
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/utils/string_util.py", line 7, in capture
    captured_text = match.group(groupnum)
AttributeError: 'NoneType' object has no attribute 'group'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19896

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 27, in attach_oss_fuzz_bug_report
    if not is_oss_fuzz_bug_report(issue):
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 40, in is_oss_fuzz_bug_report
    is_nonsecurity_bug_report = almost_equal("Bug", issue.metadata['Type'])
KeyError: 'Type'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19898

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 27, in attach_oss_fuzz_bug_report
    if not is_oss_fuzz_bug_report(issue):
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 40, in is_oss_fuzz_bug_report
    is_nonsecurity_bug_report = almost_equal("Bug", issue.metadata['Type'])
KeyError: 'Type'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19947

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 30, in attach_oss_fuzz_bug_report
    report = parse_oss_fuzz_bug_report_details(issue)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 57, in parse_oss_fuzz_bug_report_details
    crash_state = _get_crash_state(description)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 135, in _get_crash_state
    raw_crash_state = capture(description, r'Crash State:\n(.*?)\n  \n', pattern_flags=re.DOTALL)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/utils/string_util.py", line 7, in capture
    captured_text = match.group(groupnum)
AttributeError: 'NoneType' object has no attribute 'group'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19968

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 30, in attach_oss_fuzz_bug_report
    report = parse_oss_fuzz_bug_report_details(issue)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 57, in parse_oss_fuzz_bug_report_details
    crash_state = _get_crash_state(description)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 135, in _get_crash_state
    raw_crash_state = capture(description, r'Crash State:\n(.*?)\n  \n', pattern_flags=re.DOTALL)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/utils/string_util.py", line 7, in capture
    captured_text = match.group(groupnum)
AttributeError: 'NoneType' object has no attribute 'group'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19969

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 30, in attach_oss_fuzz_bug_report
    report = parse_oss_fuzz_bug_report_details(issue)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 57, in parse_oss_fuzz_bug_report_details
    crash_state = _get_crash_state(description)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 135, in _get_crash_state
    raw_crash_state = capture(description, r'Crash State:\n(.*?)\n  \n', pattern_flags=re.DOTALL)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/utils/string_util.py", line 7, in capture
    captured_text = match.group(groupnum)
AttributeError: 'NoneType' object has no attribute 'group'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19970

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 30, in attach_oss_fuzz_bug_report
    report = parse_oss_fuzz_bug_report_details(issue)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 50, in parse_oss_fuzz_bug_report_details
    project = _get_project(description, id)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 85, in _get_project
    return capture(description, r'Project: (.+?)[\n$]')
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/utils/string_util.py", line 7, in capture
    captured_text = match.group(groupnum)
AttributeError: 'NoneType' object has no attribute 'group'

ERROR:root:Exception encountered when parsing OSS-Fuzz issue 19979

ERROR:root:Traceback (most recent call last):
  File "scrape_oss_fuzz_issue_range.py", line 42, in main
    attach_oss_fuzz_bug_report(issue_i)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 30, in attach_oss_fuzz_bug_report
    report = parse_oss_fuzz_bug_report_details(issue)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 57, in parse_oss_fuzz_bug_report_details
    crash_state = _get_crash_state(description)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/oss_fuzz/oss_fuzz_bug_report_parser.py", line 135, in _get_crash_state
    raw_crash_state = capture(description, r'Crash State:\n(.*?)\n  \n', pattern_flags=re.DOTALL)
  File "/Users/zhendeveloper/Desktop/LabBox/oss-fuzz-mining/monorail-scraper/utils/string_util.py", line 7, in capture
    captured_text = match.group(groupnum)
AttributeError: 'NoneType' object has no attribute 'group'

